version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/erms
    ports:
      - '5000:5000'

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'

volumes:
  mongo-data:

